### PR TITLE
return a list of descended items 

### PR DESCRIPTION
**Pull request by stefanches7**
Noticed a small TODO, the new version lets one run `omero rdf` with no ids. (Compare before: such a run threw `variable referenced before assignment`)

I don't feel great about returning a list with the declared returning `URIRef` type, but so far it works and the integration test passes.

### CODE REVIEW

**Comment by joshmoore** [comment]
Thanks for stepping up to fix this! I think the biggest question is whether or not the command counts as an error.

A few other options that would make it an error:

 * move from `nargs="*"` to `nargs="+"` at https://github.com/German-BioImaging/omero-rdf/pull/20/files#diff-3666cb7e8845754134f23ed49a840cd508f94e8e77af558cdfdb65aba81ebf86L338
 * use `self.ctx.die` like at https://github.com/German-BioImaging/omero-rdf/pull/20/files#diff-3666cb7e8845754134f23ed49a840cd508f94e8e77af558cdfdb65aba81ebf86L445 to tell the user that there is no target
 * do something useful ?! (print help? query the whole shebang?)

Thoughts?

**Comment by stefanches7** [comment]
@joshmoore sorry, I did not get notified about this. 
Printing the help message with the requirement of targets is in my opinion the best choice here.

**Comment by joshmoore** [comment]
:+1: I think the `nargs` change should do that.

**Comment by joshmoore** [comment]
Thanks, @stefanches7!

**Pull request merged**
